export const CHANGE_TIMELINE_YEAR = "CHANGE_TIMELINE_YEAR";
export const CHANGE_FILTERS_ON_MAP = "CHANGE_FILTERS_ON_MAP";
export const MAPBOX_READY = "MAPBOX_READY";
export const RESIZE_WINDOW = "RESIZE_WINDOW";
export const MAPBOX_VIEWPORT_CHANGE = "MAPBOX_VIEWPORT_CHANGE";
export const API_GET_PHOTOPOINTS = "API_GET_PHOTOPOINTS";
export const ADD_PHOTOPOINTS_TO_MAP = "ADD_PHOTOPOINTS_TO_MAP";
export const API_GET_PHOTOPOINTS_START = "API_GET_PHOTOPOINTS_START";
export const API_GET_PHOTOPOINTS_END = "API_GET_PHOTOPOINTS_END";
export const API_GET_MAPOBJECTS = "API_GET_MAPOBJECTS";
export const ADD_MAPOBJECTS_TO_MAP = "ADD_MAPOBJECTS_TO_MAP";
export const API_GET_MAPOBJECTS_START = "API_GET_MAPOBJECTS_START";
export const API_GET_MAPOBJECTS_END = "API_GET_MAPOBJECTS_END";

export const SHOW_POPUP_PHOTO = "SHOW_POPUP_PHOTO";
export const HIDE_POPUP_PHOTO = "HIDE_POPUP_PHOTO";
export const SHOW_POPUP_RAILROAD = "SHOW_POPUP_RAILROAD";
export const HIDE_POPUP_RAILROAD = "HIDE_POPUP_RAILROAD";
export const SHOW_POPUP_MAPOBJECT = "SHOW_POPUP_MAPOBJECT";
export const HIDE_POPUP_MAPOBJECT = "HIDE_POPUP_MAPOBJECT";
export const HIDE_ALL_POPUPS = "HIDE_ALL_POPUPS";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";