export const CHANGE_TIMELINE_YEAR = "CHANGE_TIMELINE_YEAR";
export const CHANGE_FILTERS_ON_MAP = "CHANGE_FILTERS_ON_MAP";
export const MAPBOX_READY = "MAPBOX_READY";
export const RESIZE_WINDOW = "RESIZE_WINDOW";
export const MAPBOX_VIEWPORT_CHANGE = "MAPBOX_VIEWPORT_CHANGE";