export const CHANGE_TIMELINE_YEAR = "CHANGE_TIMELINE_YEAR";
export const CHANGE_FILTERS_ON_MAP = "CHANGE_FILTERS_ON_MAP";
export const MAPBOX_READY = "MAPBOX_READY";
export const RESIZE_WINDOW = "RESIZE_WINDOW";
export const MAPBOX_VIEWPORT_CHANGE = "MAPBOX_VIEWPORT_CHANGE";
export const API_GET_PHOTOPOINTS = "API_GET_PHOTOPOINTS";
export const ADD_PHOTOPOINTS_TO_MAP = "ADD_PHOTOPOINTS_TO_MAP";
export const API_GET_PHOTOPOINTS_START = "API_GET_PHOTOPOINTS_START";
export const API_GET_PHOTOPOINTS_END = "API_GET_PHOTOPOINTS_END";
export const API_GET_MAPOBJECTS = "API_GET_MAPOBJECTS";
export const ADD_MAPOBJECTS_TO_MAP = "ADD_MAPOBJECTS_TO_MAP";
export const API_GET_MAPOBJECTS_START = "API_GET_MAPOBJECTS_START";
export const API_GET_MAPOBJECTS_END = "API_GET_MAPOBJECTS_END";

export const SHOW_POPUP_PHOTO = "SHOW_POPUP_PHOTO";
export const HIDE_POPUP_PHOTO = "HIDE_POPUP_PHOTO";
export const SHOW_POPUP_RAILROAD = "SHOW_POPUP_RAILROAD";
export const HIDE_POPUP_RAILROAD = "HIDE_POPUP_RAILROAD";
export const SHOW_POPUP_MAPOBJECT = "SHOW_POPUP_MAPOBJECT";
export const HIDE_POPUP_MAPOBJECT = "HIDE_POPUP_MAPOBJECT";
export const HIDE_ALL_POPUPS = "HIDE_ALL_POPUPS";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const MAPBOX_SET_FLYTO = "MAPBOX_SET_FLYTO";
export const MAPBOX_DO_FLYTO = "MAPBOX_DO_FLYTO";

export const SHOW_STORYTELLING = "SHOW_STORYTELLING";
export const HIDE_STORYTELLING = "HIDE_STORYTELLING";

export const API_GET_RAILWAY_START = "API_GET_RAILWAY_START";
export const API_GET_RAILWAY_END = "API_GET_RAILWAY_END";
export const API_GET_RAILWAY = "API_GET_RAILWAY";

export const RAILWAY_SELECTED = "RAILWAY_SELECTED";

export const SET_DEFAULT_FLYTO = "SET_DEFAULT_FLYTO";

export const API_GET_ALBUM = "API_GET_ALBUM";
export const API_GET_ALBUM_START = "API_GET_ALBUM_START";
export const SHOW_ALBUM = "SHOW_ALBUM";
export const HIDE_ALBUM = "HIDE_ALBUM";

export const SELECT_RAILROAD = "SELECT_RAILROAD";

export const API_SEARCH_START = "API_SEARCH_START";
export const API_SEARCH_GET = "API_SEARCH_GET";
export const HIDE_SEARCH_RESULTS = "HIDE_SEARCH_RESULTS";